### ISSUE TITLE
compile yolov8 demo error!

### ISSUE THREAD

**Issue by jcyhcs** [FeiYull/TensorRT-Alpha#1]
hi,@ @FeiYull 
i compile your yolov8 demo, on windows with jetbrains CLion,I got an error:
D:\TensorRT-8.2.5.1\samples\common\sampleUtils.h(170): error: more than one operator "<<" matches these operands:
            function "std::basic_ostream<_Elem, _Traits>::operator<<(__nv_bool) [with _Elem=char, _Traits=std::char_traits<char>]"

            operand types are: std::basic_ostream<char, std::char_traits<char>> << const __half
          detected during instantiation of "void sample::dumpBuffer<T>(const void *, const std::string &, std::ostream &, const nvinfer1::Dims &, const nvinfer1::Dims &, int32_t, int32_t) [with T=__half]" 
(257): here

1 error detected in the compilation of "D:/Object_Detection/tensorrt-alpha/yolov8/decode_yolov8.cu".
decode_yolov8.cu

my tensorrt version is 8.2.5.1,
how can i resolve it? please help me!

**Comment by FeiYull** [comment]
@jcyhcs ，Hi，thanks for paying attention to TensorRT-Alpha, the problem has been fixed. The solution is simple:
 some header files under TensorRT/common are no longer included, and TensorRT-Alpha only uses logger.cpp under this path. It is recommended to use TensorRT8.4.2.4
