### ISSUE TITLE
yolov8

### ISSUE THREAD

**Issue by liuxingbo12138** [FeiYull/TensorRT-Alpha#10]
/usr/bin/ld: libyolov8.so: undefined reference to `sample::splitToStringVec(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char)'

有人报这个错误吗

**Comment by FeiYull** [comment]
@liuxingbo12138  If you are not very familiar with tensorrt, follow the documentation exactly. [https://github.com/FeiYull/TensorRT-Alpha/tree/main/Install_For_Ubuntu18.04](url)

**Comment by liuxingbo12138** [comment]
> 
thank you，i successed.

**Comment by WYQ-Github** [comment]
> > 
> 
> thank you，i successed.

您好，我也报这个错误，请问你是怎么解决的。

**Comment by FeiYull** [comment]
solution:https://github.com/FeiYull/TensorRT-Alpha/issues/47
