### ISSUE TITLE
window10 yolov8

### ISSUE THREAD

**Issue by liuxingbo12138** [FeiYull/TensorRT-Alpha#11]
![image](https://user-images.githubusercontent.com/79137028/217469055-e9c5cbd4-e995-482b-8d4f-60b3fbb06597.png)
有人遇到这个问题吗，怎么解决的

**Comment by FeiYull** [comment]
@liuxingbo12138 Looks like NVCC is not set up to compile .cu and .h files

**Comment by liuxingbo12138** [comment]
> @liuxingbo12138 Looks like NVCC is not set up to compile .cu and .h files
有交流群吗

**Comment by FeiYull** [comment]
@liuxingbo12138  #9  look at this.

**Comment by liuxingbo12138** [comment]
> @liuxingbo12138 #9 look at this.

![image](https://user-images.githubusercontent.com/79137028/218029446-6537df49-0f76-49b8-9714-a417cb5b2d41.png)
![image](https://user-images.githubusercontent.com/79137028/218029475-2a0452e1-f193-4104-a300-7daa752e5ef4.png)
您好，我想请问下按照您的教程调通了但是并没有推理出来结果，这个可能是什么原因

**Comment by FeiYull** [comment]
#10 Be solved!

**Comment by liuxingbo12138** [comment]
没太明白您的意思
