### ISSUE TITLE
yolov8 error

### ISSUE THREAD

**Issue by dadada-123** [FeiYull/TensorRT-Alpha#12]
![image](https://user-images.githubusercontent.com/93700580/217583758-44eeb665-0bf7-48dd-ba21-aa3612f7cfd2.png)
我按照视频操作编译的时候报了这个错

**Comment by FeiYull** [comment]
@dadada-123 Can you provide more detailed information? For example, to report an error code, which line of code is located？

**Comment by gongwk** [comment]
> ![image](https://user-images.githubusercontent.com/93700580/217583758-44eeb665-0bf7-48dd-ba21-aa3612f7cfd2.png) 我按照视频操作编译的时候报了这个错

I have the same problem, Maybe you can refer https://www.it1352.com/2469435.html

**Comment by wanglehui** [comment]
作者你好，能否出一个在Jetson 平台部署的教程？

**Comment by FeiYull** [comment]
@wanglehui 
ref: https://github.com/FeiYull/TensorRT-Alpha/tree/main/Install_For_Ubuntu18.04
