### ISSUE TITLE
YOLOv8-seg

### ISSUE THREAD

**Issue by ASSicat** [FeiYull/TensorRT-Alpha#124]
您好，请问我使用自己训练的权重进行推理后得到了 这样的图片这是为什么，就是分割的mask区域没有完整填充反而出现了很多斑点
![8aafa36fafa6d08197c6b0606254607](https://github.com/FeiYull/TensorRT-Alpha/assets/125629883/4126a4c3-d71a-4c38-9395-4298a76fbee0)
正常推理出来的图片应该是这样的：
![NG10  7](https://github.com/FeiYull/TensorRT-Alpha/assets/125629883/e0e153a4-9fc5-4d8a-adb1-7fd91d3d022f)
这是训练完的onnx文件以及图片放在了百度云里，太大了传不上来：
链接：https://pan.baidu.com/s/1H3QJzVXsICFqr31Ha50n4Q?pwd=kb5l 
提取码：kb5l 
--来自百度网盘超级会员V5的分享

**Comment by sctrueew** [comment]
@ASSicat Hi, have you solved your problem? I have the same issue

**Comment by kuyufei** [comment]
@sctrueew Hi, have you solved your problem? I have the same issue
