### ISSUE TITLE
yolov8's tensorRT int8 quantization

### ISSUE THREAD

**Issue by mattherdelma** [FeiYull/TensorRT-Alpha#13]
How to implement yolov8's tensorRT int8 quantization?

**Comment by FeiYull** [comment]
@mattherdelma @lyb36524 He made a FP16 quantification of the ONNX model, through the following instructions:
`./trtexec --onnx=yolov8n.onnx  --saveEngine=yolov8n_fp16.trt  --fp16 --buildOnly --minShapes=images:1x3x640x640 --optShapes=images:4x3x640x640 --maxShapes=images:8x3x640x640`
Other instructions are the same as in the link：[https://github.com/FeiYull/TensorRT-Alpha/blob/main/yolov8/README.md](url)
The figure below is the time overhead, the test device RTX4090, the BATCH_SIZE = 8：

**FP32：**
![fp32](https://user-images.githubusercontent.com/113091091/222457644-140066c9-cfcd-42f7-bd55-fc072535cab3.PNG)

**FP16：**
![fp16](https://user-images.githubusercontent.com/113091091/222457700-426140de-9596-4a35-b2eb-a2c202fb3a0b.PNG)

More quantitative tutorials, we will update in the future
