### ISSUE TITLE
你好大佬，推理结果不对，麻烦看下什么原因

### ISSUE THREAD

**Issue by dabensongbing** [FeiYull/TensorRT-Alpha#132]
我自己训练的yolov8n模型，有14个类，图像是1024*1280 的单通道图像，格式为bmp，推理后结果每个类的的置信度都是100多而且数量位置都不是很对，请问是哪里的原因，在python里验证时没有问题，部署代码除了路径没有修改过其他地方

**Comment by Wayne-zhihaozhou** [comment]
请问如何解决的.
