### ISSUE TITLE
大佬能帮忙看看后处理的rect坐标出现负数是什么问题吗

### ISSUE THREAD

**Issue by Akumio** [FeiYull/TensorRT-Alpha#148]
box-23.3341- 406.27545.2865 -325.098box32.6879 -402.85750.1109-383.296
box-48.3767- 394.05592.9195 -228.181box65.4074 -387.071101.047-346.207
[I] preprocess time = 0.84896; infer time = 3.63418; postprocess time = 0.1792
后处理视频未正常显示检测框，解析坐标出现负数

**Comment by ZSBSB** [comment]
我也遇到这个问题了，最后查出来是onx模型转换出错了。
