### ISSUE TITLE
[YOLOv5] v7.0 TensorRT support

### ISSUE THREAD

**Issue by sonderlau** [FeiYull/TensorRT-Alpha#2]
The latest verson of [YOLOv5](https://github.com/ultralytics/yolov5) is [v7.0](https://github.com/ultralytics/yolov5/releases/tag/v7.0)

I noticed that `git checkout 6.0` command is noted in YOLOv5 TensorRT README.md

It has been a few month since the v7.0 released, and due to some reasons, I have trained my model on the latest version YOLOv5 (v7.0).

I wonder whether there's a chance that this repo may add support for v7.0 of YOLOv5 ?

Any further information is helpful. Looking forward to your reply.

**Comment by FeiYull** [comment]
I haven't tried yolov5.7.0, you can give it a try, if you meet error, you can raise an issue, maybe I plan to develop compatible v5.7.0 in the future, In theory, for deployment, there is little difference

**Comment by FeiYull** [comment]
@sonderlau  Hi，TensorRT-Alpha support yolov5.7.0 and yolov5.6.0 now， Thank you for your suggestion！
This is doc：[https://github.com/FeiYull/tensorrt-alpha/blob/main/yolov5/README.md](url)

**Comment by sonderlau** [comment]
Sorry for being late, I hadn't have time to test it yet.
I'll keep you updated if anything goes wrong.
Anyway, thank you for your excellent work and your quick response.
Happy lunar new year !
