### ISSUE TITLE
模型部署

### ISSUE THREAD

**Issue by fjk123456** [FeiYull/TensorRT-Alpha#20]
您好，感谢大佬您的仓库，我已经成功在win10上跑起来了yolov8模型，有几个问题想请教下：
1、能否出一个硬件解码CUDA解码图像的教程，设置batch-size为8进行推理，CPU占用率很高，应该是因为opencv去获取图像软解码，gpu使用率有点低？
2、在具体的部署过程中，多路实时的视频鹿，一个线程接入一路视频，对应一个模型，那么batch-size就对应1咯，那这样好像加速不太明显？
3、我测试一个1分40秒的视频，虽然推理显示很快，但是log打印显示的时间长达3-4分钟，想问问这是为啥呢？因为图像存储耗时吗？
4、batch-size设置为1，进行测试，加速效果不明显，正常吗？

**Comment by FeiYull** [comment]
@fjk123456 
1. Please use deepstream instread of opencv
2. Please determine the batch according to the calculation power of your device
3. Do not visualize and save at the same time. The cases in the repository are for demonstration purposes only, and no one will use opencv to visualize and save in the project.
4. The right way to measure speed: Turn off visualization and save before doing inference.

**Comment by fjk123456** [comment]
@FeiYull 
您好，我现在重新 编译了支持cuda硬解码的opencv,版本为4.5.5，但是现在我有一个疑问：
1、就是我硬解码视频流之后，cuda_capture->nextFrame(cuda_frame)；cuda_frame.download(frame);  将gpumat直接转为mat，然后就按照您仓库中的做法进行检测，但是就算检测不到对象，我用cpu解码确实是可以检测出来的，请问您有什么建议吗？
2、或者：我直接利用GpuMat进行操作，我看您yolo推理中的copy方法，就是将cpu中图像复制到gpu中，这您有啥好的建议吗？
希望收到您的回复。。。。。。

**Comment by FeiYull** [comment]
@fjk123456 
你都已经是gpumat了，直接把数据塞进去就行了，没必要再转到CPU的Mat中
