### ISSUE TITLE
识别视频源时，会直接break。

### ISSUE THREAD

**Issue by ZJDATY** [FeiYull/TensorRT-Alpha#22]
`yolov8.exe  --model=yolov8n.trt --size=640 --batch_size=1  --video=http://10.100.55.191:8081/video  --show`

我设置了这样的输入参数，他会在下面这处返回。然后我把他注释掉，就可以了 。
![image](https://user-images.githubusercontent.com/29767049/227155297-7ed38735-5917-4a46-9183-0a0833a51cbf.png)

我这种简单粗暴的方法是不是有问题，麻烦能增加直播源的检测吗 。

**Comment by FeiYull** [comment]
@ZJDATY  Support infer picture, video file or camera video stream, but please note that the above are based on opencv, I'm not sure if opencv meets your needs, maybe deepstream or gstream.
