### ISSUE TITLE
使用自己訓練的模型準度大幅下降

### ISSUE THREAD

**Issue by pigking0126** [FeiYull/TensorRT-Alpha#27]
使用yolov8n訓練出的模型(class只有1)，使用python_with_dll測試部屬，推理準度與原本差非常多，想請問是否有哪裡需要隨著模型修改?

**Comment by FeiYull** [comment]
@pigking0126  ref: https://b23.tv/llaLnqB

**Comment by pigking0126** [comment]
成功了!!謝謝大佬!!
