### ISSUE TITLE
使用ultralytics反而略快，是否有哪裡沒處理好

### ISSUE THREAD

**Issue by pigking0126** [FeiYull/TensorRT-Alpha#29]
使用顯卡3060，輸入圖片為640*640的numpy.ndarray

![螢幕擷取畫面 (16)](https://user-images.githubusercontent.com/130830154/232958377-874ab8e6-86d2-4c81-80a5-1293eac90be0.png)
這是使用官方一條龍的，包含轉檔成engine、推理
![螢幕擷取畫面 (15)](https://user-images.githubusercontent.com/130830154/232958380-0750b653-6e1f-4611-803f-d0d2bd0a5427.png)
這是編譯成dll後從python呼叫的，模型轉換、推理都是使用TensorRT-Alpha

兩者模型皆使用fp16
可以看出使用此版本慢於ultralytics的tensorrt
但引用ultralytics實在太臃腫
使用大佬的舒服多了
想請問大佬如果只需要得到物件座標，是否有哪裡可以優化，或是我原本就有哪裡可能沒做好?

**Comment by FeiYull** [comment]
@pigking0126  
How do you calculate code runtime? 
 RTX3060 graphics card performs better than the mobile RTX2070m, the former theory should be faster，The following is the measured performance of RTX2070m：

![RTX2070m](https://user-images.githubusercontent.com/113091091/232960473-7b51a6c4-1165-4141-b47a-83cfe11a1187.png)


![yolov8n-b8-1080p-to-640](https://user-images.githubusercontent.com/113091091/232960487-e9202532-956b-4bde-8842-fb001f5df794.jpg)

**Comment by FeiYull** [comment]
@shancw96  @pigking0126  Could you give him some advice？

**Comment by FeiYull** [comment]
@pigking0126  A known reason is: it uses multi-threaded technology to copy data to the gpu, while the warehouse is single-threaded.
https://github.com/FeiYull/TensorRT-Alpha/blob/ffa90c0218005703bb52333fd24bb81c768cf28f/utils/yolo.cpp#L151
You need to modify it yourself, it should be easy

**Comment by shancw96** [comment]
> @shancw96  @pigking0126  Could you give him some advice？

The img batch is cast to 1 in demo c file, maybe this caused that problem? @FeiYull 
I'm not a pro in this field so what happened when work with gpu i don't know either.😅

**Comment by pigking0126** [comment]
> @pigking0126 How do you calculate code runtime? 
I didn't change time calculating method in both ultralytics' and this repo's. 
The img use in my code is screenshot and inference in numpy.ndarray one by one, so maybe not because of threading or batchsize? (I'm not sure.)
Still working on it.

**Comment by shancw96** [comment]
https://github.com/FeiYull/TensorRT-Alpha/blob/ffa90c0218005703bb52333fd24bb81c768cf28f/examples/python_with_dll/c_files/pch.cpp#L84-L91

the demo calculation can be found here, emmm....  just copy from yolov8 cpp version, the img batch alway 1, so i remove it.

https://github.com/FeiYull/TensorRT-Alpha/blob/4b50b83e7af896e78b656d26fbb81691e5848399/yolov8/app_yolov8.cpp#L22-L27

**Comment by pigking0126** [comment]
It seems to because i use debug x64 to build cause it so slow...... I use release x64 and everything works well. lol
![螢幕擷取畫面 (19)](https://user-images.githubusercontent.com/130830154/233638169-fbf19100-0047-47ad-8ff1-095cbc5e318b.png)
Sorry about the time I waste...
