### ISSUE TITLE
支持yolov8的实例分割部署吗

### ISSUE THREAD

**Issue by aiwenzhu** [FeiYull/TensorRT-Alpha#31]

**Comment by Lishumuzixin** [comment]
> @aiwenzhu do it in the future

请问现在支持yolov8实例分割了么

**Comment by FeiYull** [comment]
@Lishumuzixin  分割 姿态检测 分类 跟踪已经做完，整理好更新哦

**Comment by Lishumuzixin** [comment]
你好，现在还没更新是么？先码一个



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: FeiYull ***@***.***&gt;
发送时间: 2023年11月2日 16:00
收件人: FeiYull/TensorRT-Alpha ***@***.***&gt;
抄送: Lishumuzixin ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [FeiYull/TensorRT-Alpha] 支持yolov8的实例分割部署吗 (Issue #31)





 
@Lishumuzixin  分割 姿态检测 分类 跟踪已经做完，整理好更新哦

**Comment by gaowq2017** [comment]
@FeiYull 请问yolov8实例分割代码什么时候更新？
