### ISSUE TITLE
The resizeimg input here is a fixed value of 114, shouldn't it be adapted based on different images

### ISSUE THREAD

**Issue by ZJDATY** [FeiYull/TensorRT-Alpha#33]
```
void YOLOV8::preprocess(const std::vector<cv::Mat>& imgsBatch)
{
    // 1.resize
    resizeDevice(m_param.batch_size, m_input_src_device, m_param.src_w, m_param.src_h,
        m_input_resize_device, m_param.dst_w, m_param.dst_h, 114, m_dst2src);
```
Also, I don't quite understand the principle of how to construct utils: AffineMat matrix. Isn't the image affine transformation a 3x3 matrix with 6 unknowns. Is it possible to use a 2x2 scaling matrix. I don't quite understand the meaning of the third column of numbers, or rather, I don't quite understand this matrix.

![image](https://github.com/FeiYull/TensorRT-Alpha/assets/29767049/d745615f-04e5-42c6-aea5-02600c38d4d9)

![image](https://github.com/FeiYull/TensorRT-Alpha/assets/29767049/53d0ae69-26b3-43b6-a5c8-e9bb696b4843)

![image](https://github.com/FeiYull/TensorRT-Alpha/assets/29767049/d1210821-54c3-4802-9812-81f969b7dc78)

**Comment by FeiYull** [comment]
@ZJDATY 
![1389269-20230119135633591-1420057710](https://github.com/FeiYull/TensorRT-Alpha/assets/113091091/ae31e57a-b505-4d9c-bac3-70c9cab1b76f)

**Comment by FeiYull** [comment]
https://github.com/FeiYull/TensorRT-Alpha/blob/ffa90c0218005703bb52333fd24bb81c768cf28f/utils/kernel_function.h#L49

resizeDevice has the same effect as cv::resize(), both are  fixed padding values(114).
