### ISSUE TITLE
yolov8编译完成运行报错

### ISSUE THREAD

**Issue by AndroidLwk** [FeiYull/TensorRT-Alpha#34]
FAILED: app_yolov8 
: && /usr/bin/c++ -Wno-error=deprecated-declarations -Wno-deprecated-declarations  -g  CMakeFiles/app_yolov8.dir/app_yolov8.cpp.o -o app_yolov8  -Wl,-rpath,/home/hy-20/project/TensorRT-Alpha/yolov8/cmake-build-debug:/home/hy-20/TensorRT-8.5.3.1/lib:/usr/local/cuda-11.8/lib64:/home/hy-20/opencv-4.5.5/build/lib  libyolov8.so  /usr/local/cuda-11.8/lib64/libcudart_static.a  -ldl  /usr/lib/x86_64-linux-gnu/librt.so  /usr/local/cuda-11.8/lib64/libcublas.so  /usr/local/cuda-11.8/lib64/libnppc.so  /usr/local/cuda-11.8/lib64/libnppig.so  /usr/local/cuda-11.8/lib64/libnppidei.so  /usr/local/cuda-11.8/lib64/libnppial.so  /home/hy-20/TensorRT-8.5.3.1/lib/libnvinfer.so  /home/hy-20/TensorRT-8.5.3.1/lib/libnvinfer_plugin.so  /home/hy-20/TensorRT-8.5.3.1/lib/libnvonnxparser.so  /home/hy-20/TensorRT-8.5.3.1/lib/libnvcaffe_parser.so  /home/hy-20/opencv-4.5.5/build/lib/libopencv_stitching.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_aruco.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_barcode.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_bgsegm.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_bioinspired.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_ccalib.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_dnn_objdetect.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_dnn_superres.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_dpm.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_face.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_freetype.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_fuzzy.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_hfs.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_img_hash.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_intensity_transform.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_line_descriptor.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_mcc.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_quality.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_rapid.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_reg.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_rgbd.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_saliency.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_stereo.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_structured_light.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_superres.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_surface_matching.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_tracking.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_videostab.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_wechat_qrcode.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_xfeatures2d.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_xobjdetect.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_xphoto.so.4.5.5  -lpthread  /home/hy-20/opencv-4.5.5/build/lib/libopencv_phase_unwrapping.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_optflow.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_highgui.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_datasets.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_plot.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_text.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_videoio.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_ml.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_shape.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_ximgproc.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_video.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_imgcodecs.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_objdetect.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_calib3d.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_dnn.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_features2d.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_flann.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_photo.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_imgproc.so.4.5.5  /home/hy-20/opencv-4.5.5/build/lib/libopencv_core.so.4.5.5 && :
/usr/bin/ld: libyolov8.so: undefined reference to `sample::splitToStringVec(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char)'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

请问这是因为环境版本不匹配还是因为什么啊？

**Comment by xiaohaoo** [comment]
@AndroidLwk 少链接库了，sample::splitToStringVec找不到

**Comment by tchen-tt** [comment]
我也是同样的问题，这个问题你解决了吗？

**Comment by sang8052** [comment]
我也包这个错，请问是少了什么库文件导致的呢

**Comment by FeiYull** [comment]
solution:https://github.com/FeiYull/TensorRT-Alpha/issues/47
