### ISSUE TITLE
yolov8模型转换相关

### ISSUE THREAD

**Issue by lzcchl** [FeiYull/TensorRT-Alpha#43]
我下载了7月份yolov8官方模型，pt转onnx成功，但是onnx转trt失败；
我看了一下你博客的评论，也有人onnx转trt失败，说是版本要保持一致，我的软件版本都是和一样的，ultralytics==8.0.5，只有yolo的pt是最新的，所以是yolov8模型结构变了么？
那么我怎么样才能下载到ultralytics==8.0.5版本的yolo官方权重呢。

**Comment by FeiYull** [comment]
@lzcchl 今天试了下，没有问题的，tensorrt测试版本：8.4.2.4
