### ISSUE TITLE
win10系统下Cmake error

### ISSUE THREAD

**Issue by jithf** [FeiYull/TensorRT-Alpha#45]
当我按如下操作执行时：
git clone https://github.com/FeiYull/tensorrt-alpha
cd tensorrt-alpha/yolov8
mkdir build
cd build
cmake ..

cmake 报错：
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
TRT_NVCAFFE_PARSER
    linked by target "yolov8" in directory E:/software/anconda/.conda/envs/yolov8/tensorrt-alpha/yolov8
    linked by target "app_yolov8" in directory E:/software/anconda/.conda/envs/yolov8/tensorrt-alpha/yolov8

cmake版本已更新至最新版，此error仍存在，不知该如何解决？

**Comment by FeiYull** [comment]
@jithf  ref：https://blog.csdn.net/m0_72734364/article/details/128865904?csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22128865904%22%2C%22source%22%3A%22m0_72734364%22%7D&fromshare=blogdetail

**Comment by Sencc** [comment]
请问你解决了吗

**Comment by VguanwenV** [comment]
win10上遇到相同的问题
