### ISSUE TITLE
[Windows] Infer time too long

### ISSUE THREAD

**Issue by MangoloD** [FeiYull/TensorRT-Alpha#46]
When testing on Windows, it seems like there was a problem with the infer time, but I don't know where the problem came from
![image](https://github.com/FeiYull/TensorRT-Alpha/assets/52820275/92f7dd6e-4c50-4d5e-8fff-ea60b328db19)

**Comment by FeiYull** [comment]
@MangoloD  You need to warm up before doing inference with  only one picture. Try to infer a video.

**Comment by MangoloD** [comment]
I got it！Thanks!

**Comment by MangoloD** [comment]
> @MangoloD You need to warm up before doing inference with only one picture. Try to infer a video.

I got it ! Thanks !
