### ISSUE TITLE
undefined reference to `sample::splitToStringVec 哪里不对呢？

### ISSUE THREAD

**Issue by wangyong5123** [FeiYull/TensorRT-Alpha#47]
[ 90%] Building CXX object CMakeFiles/app_yolov8.dir/app_yolov8.cpp.o
[100%] Linking CXX executable app_yolov8
/usr/bin/ld: libyolov8.so: undefined reference to `sample::splitToStringVec(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/app_yolov8.dir/build.make:163：app_yolov8] 错误 1
make[1]: *** [CMakeFiles/Makefile2:111：CMakeFiles/app_yolov8.dir/all] 错误 2
make: *** [Makefile:91：all] 错误 2

**Comment by territoryLiu** [comment]
Add sampleUtils.cpp to the Tensorrt section in cmakelists.
![image](https://github.com/FeiYull/TensorRT-Alpha/assets/65395321/60a71a1d-dc97-4586-9426-ac07623c3402)

**Comment by kkboy771** [comment]
Add sampleUtils.cpp to the Tensorrt section in cmakelists. Still haven't solved the problem
![Uploading a49776088915f5dc7ea44fa19a4f2690.png…]()

**Comment by FunnyWii** [comment]
me too

**Comment by FunnyWii** [comment]
The solution provided by author works well.
You need to confirm the path of TensorRT in common.cmake.
Then empty your build folder and rebuild it.
If still doesn't work, re-pull this repo and do above works.
