### ISSUE TITLE
Error with dynamic batch image processing in TensorRT-Alpha

### ISSUE THREAD

**Issue by Droxico** [FeiYull/TensorRT-Alpha#5]
I am trying to use the dynamic batch image processing feature in TensorRT-Alpha but am encountering an error. I have followed the instructions provided in the repository and have successfully exported the ONNX file, but when I try to run the image processing code I am getting an error. Can you please provide assistance in resolving this issue? Thank you.

**Comment by FeiYull** [comment]
@Droxico Hi, Can you provide detailed error message?
