### ISSUE TITLE
【utils/yolo.cpp】代码请教

### ISSUE THREAD

**Issue by MMmingming** [FeiYull/TensorRT-Alpha#65]
你好，请问utils/yolo.cpp中，这里的m_output_objects_width = 7 如何理解。
如果是每个目标信息应该等于 4+ cls的大小吗，虽然跑的结果正确但这里不太理解，希望能够解答谢谢！

https://github.com/FeiYull/TensorRT-Alpha/blob/ade5898a58e10580d555a3ded5fa630ec2eeee70/utils/yolo.cpp#L21C23-L21C23

**Comment by FeiYull** [comment]
@MMmingming   7:left, top, right, bottom, confidence, class, keepflag;

**Comment by MMmingming** [comment]
@FeiYull thanks！
