### ISSUE TITLE
Trying to run YOLOv4 model on TensorRT-Alpha

### ISSUE THREAD

**Issue by ZyLi99** [FeiYull/TensorRT-Alpha#7]
I am trying to use the YOLOv4 model provided in the TensorRT-Alpha repository, but I am encountering an error when trying to run the inference. Specifically, I am getting the following message: 'CUDA error: invalid device function'. I have double-checked that my CUDA version is compatible with the code and that my GPU is properly configured. I would appreciate any help in resolving this issue.

**Comment by FeiYull** [comment]
#8
