### ISSUE TITLE
u2net编译有问题

### ISSUE THREAD

**Issue by a819411321** [FeiYull/TensorRT-Alpha#76]
VS2022报错无效的数值参数“/Wno-deprecated-declarations”

**Comment by FeiYull** [comment]
@a819411321 试下在代码第一行加上如下

#define _CRT_SECURE_NO_WARNINGS

**Comment by a819411321** [comment]
> @a819411321 试下在代码第一行加上如下
> 
> #define _CRT_SECURE_NO_WARNINGS

ok解决了  谢谢大佬
