### ISSUE TITLE
Trouble about running the NMS function

### ISSUE THREAD

**Issue by anqi666** [FeiYull/TensorRT-Alpha#8]
I am having trouble running the NMS function in the TensorRT-Alpha repository. I am getting an error message related to CUDA support, and I am not sure what the issue is. Can you please provide guidance on how to resolve this issue? Thank you.

**Comment by FeiYull** [comment]
@anqi666 hi, TensorRT8.4.2.4 support  CUDA 11.0, 11.1, 11.2, 11.3, 11.4, 11.5, 11.6 and 11.7.
You can use the following command to verify whether the driver and cuda are installed normally：
`nvidia-smi``nvcc -V`
reference：[https://github.com/FeiYull/TensorRT-Alpha/blob/main/Install_For_Ubuntu18.04/Install_For_Ubuntu18.04.md](url)
