### ISSUE TITLE
yolov5s推理视频流过程中，imshow界面突然卡住，但终端命令行继续输出

### ISSUE THREAD

**Issue by Deephome** [FeiYull/TensorRT-Alpha#80]
你好，推理网络相机rtsp视频流，imshow图像界面中途卡住，但终端命令行继续输出。请问有什么建议吗，谢谢！

**Comment by FeiYull** [comment]
@Deephome 环境是？opencv是源码编译的吗？

**Comment by Deephome** [comment]
@FeiYull 自己程序有bug，已解决，谢谢！
