### ISSUE TITLE
Multi times deserializeCudaEngine 

### ISSUE THREAD

**Issue by Ichiruchan** [FeiYull/TensorRT-Alpha#91]
您好，在您的YOLOv8 pose代码中
```
bool YOLOv8Pose::init(const std::vector<unsigned char>& trtFile)
{
    if (trtFile.empty())
    {
        return false;
    }
    std::unique_ptr<nvinfer1::IRuntime> runtime =
        std::unique_ptr<nvinfer1::IRuntime>(nvinfer1::createInferRuntime(sample::gLogger.getTRTLogger()));
    if (runtime == nullptr)
    {
        return false;
    }
    this->m_engine = std::unique_ptr<nvinfer1::ICudaEngine>(runtime->deserializeCudaEngine(trtFile.data(), trtFile.size()));
    if (this->m_engine == nullptr)
    {
        return false;
    }
    this->m_context = std::unique_ptr<nvinfer1::IExecutionContext>(this->m_engine->createExecutionContext());
    if (this->m_context == nullptr)
    {
        return false;
    }
``` 
初始化函数中有这样的反序列化读取模型的代码，由于我的预测的每张图大小不一样，且初始化时会针对其大小开辟显存空间，且我的无法一口气获取所有的图片，是在一个循环中一张一张图进来的，所以batch_size=1，这样导致对于每一张图我都要新建一个yolo_pose对象，而其中反序列话的耗时尤为突出，所以我重载了init
```
bool YOLOv8Pose::init(nvinfer1::ICudaEngine* trtEngine)
{
    this->m_engine = std::unique_ptr<nvinfer1::ICudaEngine>(trtEngine);;
    if (this->m_engine == nullptr)
    {
        return false;
    }
    this->m_context = std::unique_ptr<nvinfer1::IExecutionContext>(this->m_engine->createExecutionContext());
    if (this->m_context == nullptr)
    {
        return false;
    }
.......
调用代码
 //if (trt_file.empty())
//{
//	sample::gLogError << "trt_file is empty!" << std::endl;
//	return -1;
//}
//std::unique_ptr<nvinfer1::IRuntime> runtime =
//	std::unique_ptr<nvinfer1::IRuntime>(nvinfer1::createInferRuntime(sample::gLogger.getTRTLogger()));
//if (runtime == nullptr)
//{
//	return -1;
//}
//nvinfer1::ICudaEngine* trtEngine = runtime->deserializeCudaEngine(trt_file.data(), trt_file.size());

for （）{...}

```
我将runtime与反序列化放在了外部，但是结果发现行不通，在循环中似乎runtime被自动释放了，

**Comment by FeiYull** [comment]
@Ichiruchan 试一下https://github.com/FeiYull/TensorRT-Alpha/issues/90

**Comment by FeiYull** [comment]
@Ichiruchan 一点理解：假定输入10张图，每张图的分辨率都不一样；推理之前，都会resize+padding成为640X640分辨率的图；所以需要做到如下两点：

1. 在for循环中，动态申请显存，用于存放图片数据；
2. 在for循环中，每次都要计算 src2dst ，如下代码，由于是默认每张图宽高一致，只需要计算一次；
https://github.com/FeiYull/TensorRT-Alpha/blob/87fdb72056682835ab06e417f7d51f483e197ebf/utils/yolo.cpp#L90

**Comment by Ichiruchan** [comment]
发生问题时的变量声明和issue90中一样，我认为反序列化模型和动态申请显存和计算src2dst是可以分离的，所以除去反序列化的步骤，剩余的动态申请显存和计算都按照原有代码运行

**Comment by FeiYull** [comment]
@Ichiruchan  runtime放到类中，声明为成员试试

**Comment by Ichiruchan** [comment]
> @Ichiruchan runtime放到类中，声明为成员试试
```
yolo.h中
protected:
    std::shared_ptr<nvinfer1::ICudaEngine> m_engine;
    std::unique_ptr<nvinfer1::IExecutionContext> m_context;
    std::unique_ptr<nvinfer1::IRuntime> m_runtime;

yolov8_pose.h中
virtual bool init(nvinfer1::IRuntime* runtime, nvinfer1::ICudaEngine* trtEngine);
yolov8_cpp.中

bool YOLOv8Pose::init(nvinfer1::IRuntime* runtime, nvinfer1::ICudaEngine* trtEngine)
{
    this->m_runtime = std::unique_ptr<nvinfer1::IRuntime>(runtime);
    this->m_engine = std::unique_ptr<nvinfer1::ICudaEngine>(trtEngine);
    this->m_context = std::unique_ptr<nvinfer1::IExecutionContext>(this->m_engine->createExecutionContext());

调用时
nvinfer1::IRuntime* runtime = nvinfer1::createInferRuntime(sample::gLogger.getTRTLogger());
nvinfer1::ICudaEngine* trtEngine = runtime->deserializeCudaEngine(trt_file.data(), trt_file.size());
传入
```
依旧是产生了指针的问题

**Comment by Ichiruchan** [comment]
在循环的第二次中
<img width="928" alt="企业微信截图_17091756055470" src="https://github.com/FeiYull/TensorRT-Alpha/assets/61850562/10727cb3-d8aa-4702-9355-781db5d18951">
发生了空指针问题

**Comment by FeiYull** [comment]
@Ichiruchan 
试一下去掉智能指针
声明：
nvinfer1::ICudaEngine*  m_engine;
nvinfer1::IExecutionContext*  m_context;
nvinfer1::IRuntime* m_runtime;

释放（写在析构函数）：
m_runtime->destroy();
m_engine->destroy();
m_context->destroy();

**Comment by Ichiruchan** [comment]
ok，解决方案如下，只需要将engine指针改回为普通指针（其他成员无需变动，与作者原有的一样即可），在析构时将其设置为nullptr，最后在外部destroy runtime和trtengine即可
```
nvinfer1::ICudaEngine* m_engine;

```

**Comment by Ichiruchan** [comment]
目前发现了一些新情况，在调用`trtengine->destroy(), runtime->destroy()`后，这两个值的地址并非为0x0000000，这样是否正常

**Comment by FeiYull** [comment]
声明顺序是 &nbsp;a b c，释放顺序就是 &nbsp;c b a




FeiYull
***@***.***




------------------ Original ------------------
From: Yiru SHEN ***@***.***&gt;
Date: Thu,Feb 29,2024 6:05 PM
To: FeiYull/TensorRT-Alpha ***@***.***&gt;
Cc: FeiYull ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [FeiYull/TensorRT-Alpha] Multi times deserializeCudaEngine (Issue #91)
